services:
  - type: web
    name: ai-agent-gemini
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyBGbHn9JTXxQ13jWzMzKl7MFP1OTMXYx1A
      - key: REDIS_URL
        value: redis://redis:6379

  - type: redis
    name: redis
